### ISSUE TITLE
Patchable for Box ignores BoxChildProperties?

### ISSUE THREAD

**Issue by niteria** [owickstrom/gi-gtk-declarative#51]
I was trying to understand how the pieces fit together and looking at the implementation of Patchable for Box got me wondering why BoxChildProperties isn't taken into account.

I don't have a real world example that demonstrates it should be, but I can come up with something contrived that demonstrates the need. Say the padding property is derived from the current application state. IIUC (and a simple program seems to confirm this) an empty patch will be computed and nothing will update.

Am I misunderstanding something?

(Btw, thank you for the library, the library looks awesome, I really want to try building UIs in this style)

**Comment by owickstrom** [comment]
Oh, I think you are right. https://github.com/owickstrom/gi-gtk-declarative/blob/master/gi-gtk-declarative/src/GI/Gtk/Declarative/Container/Box.hs#L54 is missing updates for the properties. I'm not sure we can update the box packing properties without removing the children and readding them, though.

BTW, I've been working on a property-based testing setup which actually runs GTK so that we can test this library properly. I'll try to reproduce this particular problem in such a test.

**Comment by owickstrom** [comment]
If you want to try fixing the issue in the meantime, that would be very welcome. Thanks for the kind words!
